name: Build Vectorizer EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pillow pyqt5

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --noconfirm --onefile --windowed vectorizer.py

      - name: Upload EXE
        uses: actions/upload-artifact@v3.1.3
        with:
          name: vectorizer-exe
          path: dist/vectorizer.exe
